### ISSUE TITLE
We might need to configure "cloud.aws.stack.auto=false" in local.

### ISSUE THREAD

**Issue by akiraabe** [Fintan-contents/spring-crib-notes#8]
I tried using AWS S3 from SpringBoot web application.
In the local environment, I needed to  add "cloud.aws.stack.auto=false" in my application.properties.

regards.

**Comment by charon-r13b** [comment]
The current documentation is based on the Spring Cloud Release Train "Finchley".

[動作確認環境と依存ライブラリについて](https://fintan-contents.github.io/spring-crib-notes/latest/html/about/index.html#test-environment-and-dependencies)

The event you reported appears to occur after Release Train "Greenwich". It did not occur with Release Train "Finchley".

Sorry, the documentation has not updated Spring Boot and Spring Cloud. I'd like to add the reported properties when updating the documentation.

Thanks.

**Comment by charon-r13b** [comment]
This problem will always be encountered when updating the library when updating the documentation, so fix it accordingly.

This issue will be closed this time.

Thank you for your report.
